//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {

	private NewDataSetTable[] itemsField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("Table", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public NewDataSetTable[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NewDataSetTable {

	private string sEQUENCENAMEField;

	private int bOOKNUMBERField;

	private bool bOOKNUMBERFieldSpecified;

	private long aLLOCATIONNOField;

	private bool aLLOCATIONNOFieldSpecified;

	private long rNGLOField;

	private bool rNGLOFieldSpecified;

	private long rNGHIField;

	private bool rNGHIFieldSpecified;

	private long rNGLASTField;

	private bool rNGLASTFieldSpecified;

	private string pREFIXField;

	private string sUFFIXField;

	private string uNITSERIALField;

	private System.DateTime lASTUNLOADDATEField;

	private bool lASTUNLOADDATEFieldSpecified;

	private System.DateTime dELETEDDATEField;

	private bool dELETEDDATEFieldSpecified;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string SEQUENCENAME {
		get {
			return this.sEQUENCENAMEField;
		}
		set {
			this.sEQUENCENAMEField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public int BOOKNUMBER {
		get {
			return this.bOOKNUMBERField;
		}
		set {
			this.bOOKNUMBERField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool BOOKNUMBERSpecified {
		get {
			return this.bOOKNUMBERFieldSpecified;
		}
		set {
			this.bOOKNUMBERFieldSpecified = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public long ALLOCATIONNO {
		get {
			return this.aLLOCATIONNOField;
		}
		set {
			this.aLLOCATIONNOField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool ALLOCATIONNOSpecified {
		get {
			return this.aLLOCATIONNOFieldSpecified;
		}
		set {
			this.aLLOCATIONNOFieldSpecified = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public long RNGLO {
		get {
			return this.rNGLOField;
		}
		set {
			this.rNGLOField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool RNGLOSpecified {
		get {
			return this.rNGLOFieldSpecified;
		}
		set {
			this.rNGLOFieldSpecified = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public long RNGHI {
		get {
			return this.rNGHIField;
		}
		set {
			this.rNGHIField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool RNGHISpecified {
		get {
			return this.rNGHIFieldSpecified;
		}
		set {
			this.rNGHIFieldSpecified = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public long RNGLAST {
		get {
			return this.rNGLASTField;
		}
		set {
			this.rNGLASTField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool RNGLASTSpecified {
		get {
			return this.rNGLASTFieldSpecified;
		}
		set {
			this.rNGLASTFieldSpecified = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string PREFIX {
		get {
			return this.pREFIXField;
		}
		set {
			this.pREFIXField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string SUFFIX {
		get {
			return this.sUFFIXField;
		}
		set {
			this.sUFFIXField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string UNITSERIAL {
		get {
			return this.uNITSERIALField;
		}
		set {
			this.uNITSERIALField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public System.DateTime LASTUNLOADDATE {
		get {
			return this.lASTUNLOADDATEField;
		}
		set {
			this.lASTUNLOADDATEField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool LASTUNLOADDATESpecified {
		get {
			return this.lASTUNLOADDATEFieldSpecified;
		}
		set {
			this.lASTUNLOADDATEFieldSpecified = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public System.DateTime DELETEDDATE {
		get {
			return this.dELETEDDATEField;
		}
		set {
			this.dELETEDDATEField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool DELETEDDATESpecified {
		get {
			return this.dELETEDDATEFieldSpecified;
		}
		set {
			this.dELETEDDATEFieldSpecified = value;
		}
	}
}
